spring.application.name=springboot-mvc

# jsp 配置
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# 啟用 hiddenmethodfilter
spring.mvc.hiddenmethod.filter.enabled=true

# mysql 配置
spring.datasource.url=jdbc:mysql://localhost:3306/web?useSSL=false&serverTimezone=Asia/Taipei&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
spring.datasource.username=web
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
